USE Remote_Health_Monitoring;
CREATE TABLE PATIENT_DETAILS(DETAIL_ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,PATIENT_ID INT NOT NULL  ,TEMPERATUR INT NOT NULL,PULSE_RATE INT NOT NULL,OXYGEN_L INT NOT NULL,TIME_STAMP TIME NOT NULL);
ALTER TABLE PATIENT_DETAILS AUTO_INCREMENT=10000;
SELECT * FROM PATIENT_DETAILS;
ALTER TABLE PATIENT_DETAILS
ADD FOREIGN KEY (PATIENT_ID) REFERENCES patient(PATIENT_ID);
SELECT * FROM PATIENT_DETAILS;
INSERT INTO PATIENT_DETAILS(PATIENT_ID,TEMPERATUR,PULSE_RATE,OXYGEN_L,TIME_STAMP) VALUES(1000,37,95,92,'15:30:35');
INSERT INTO PATIENT_DETAILS(PATIENT_ID,TEMPERATUR,PULSE_RATE,OXYGEN_L,TIME_STAMP) VALUES(1001,37,95,92,'15:30:35');
INSERT INTO PATIENT_DETAILS(PATIENT_ID,TEMPERATUR,PULSE_RATE,OXYGEN_L,TIME_STAMP) VALUES(1002,37,95,92,'15:30:35');
SELECT * FROM PATIENT_DETAILS;

