USE Remote_Health_Monitoring;

CREATE TABLE PATIENT (PATIENT_ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,PATIENT_FULL_NAME VARCHAR(50) NOT NULL,EMAIL_ID VARCHAR(50) NOT NULL, AGE INT NOT NULL, GENDER CHAR NOT NULL,ADDRESS VARCHAR(150) NOT NULL,PHONE_NO VARCHAR(10) NOT NULL,DOB DATE NOT NULL,BLOOD_GROUP VARCHAR(4) NOT NULL );
SELECT * FROM PATIENT;
ALTER TABLE PATIENT AUTO_INCREMENT=1000;
INSERT INTO PATIENT(PATIENT_FULL_NAME ,EMAIL_ID , AGE, GENDER ,ADDRESS,PHONE_NO ,DOB,BLOOD_GROUP) VALUES("test_patient1","test_patient1@gmail.com",20,'M',"test_adress patient 1","1234567891",'2000-12-31',"O+");
SELECT * FROM PATIENT;
INSERT INTO PATIENT(PATIENT_FULL_NAME ,EMAIL_ID , AGE, GENDER ,ADDRESS,PHONE_NO ,DOB,BLOOD_GROUP) VALUES("test_patient2","test_patient1@gmai2.com",21,'M',"test_adress patient 2","2345678912",'2000-12-31',"AB-");
INSERT INTO PATIENT(PATIENT_FULL_NAME ,EMAIL_ID , AGE, GENDER ,ADDRESS,PHONE_NO ,DOB,BLOOD_GROUP) VALUES("test_patient3","test_patient1@gmai3.com",22,'M',"test_adress patient 3","3456789123",'2000-12-31',"Rh-");
INSERT INTO PATIENT(PATIENT_FULL_NAME ,EMAIL_ID , AGE, GENDER ,ADDRESS,PHONE_NO ,DOB,BLOOD_GROUP) VALUES("test_patient4","test_patient1@gmai4.com",23,'M',"test_adress patient 4","4567891234",'2000-12-31',"B+");

SELECT * FROM PATIENT;